language: cpp
compiler:
  - gcc
before_script:
#  - sudo apt-get update
#  - sudo apt-get -o Dpkg::Options::="--force-confnew" upgrade
  - sudo apt-get install libxml2-utils
  - mkdir -p ~/my_rel ~/my_build
  - ./admin/builders/ubuntu64_build.sh -s `pwd`/.. -r ~/my_rel -b ~/my_build
# Change this to your needs
script:  cd ~/my_build/percolator && sudo make install && make test ARGS="-V"
