name: native windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: create_dirs
      run: mkdir ..\my_rel ..\my_build
    - name: configure_and_make
      run: .\admin\builders\nativew64_build.sh -s .. -r ..\my_rel -b ..\my_build
    - name: cd_to_build
      run: cd ..\my_build\percolator
    - name: install
      run: make install
    - name: test
      run: make test ARGS="-V"
